### ISSUE TITLE
Allow redirect_uri's like "x-cyberduck-action:oauth"

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/oauth2#364]
Cyberduck & Mountain Duck now support WebDAV with OAuth 2.0 / OpenID Connect:
- https://github.com/iterate-ch/cyberduck/issues/14876
- https://github.com/iterate-ch/cyberduck/pull/14877

Sadly, redirect_uri's like `x-cyberduck-action:oauth` or `x-mountainduck-action:oauth` can't be added to `OAuth2 0.6.1` settings on `ownCloud 10.13.2`

### Steps to reproduce
1. Enable `OAuth2 0.6.1`
3. Login as admin user and go to `/settings/admin?sectionid=authentication`
4. Add Client with `redirect_uri=x-cyberduck-action:oauth`

### Expected behaviour
I should be able to create a new client with `redirect_uri=x-cyberduck-action:oauth`

### Actual behaviour
Error message: `Redirect URI must be a valid URL`

### Server configuration

```
{
  "installed": true,
  "maintenance": false,
  "needsDbUpgrade": false,
  "version": "10.13.2.3",
  "versionstring": "10.13.2",
  "edition": "Enterprise",
  "productname": "ownCloud",
  "product": "ownCloud"
}
```

![CleanShot 2023-11-02 at 19 05 13@2x](https://github.com/owncloud/oauth2/assets/214010/a963c6c5-b7a3-4846-97bc-d08ae9fed8ae)

@DeepDiver1975

/cc @dkocher FYI

**Comment by michaelstingl** [comment]
Same with [`occ oauth2` command](https://doc.owncloud.com/server/10.13/admin_manual/configuration/server/occ_command.html#oauth2):

```
root@owncloud:~/server# docker-compose exec owncloud occ oauth2:add-client Cyberduck 3keLfua0olYvW1zKXTDB3OjAMPEYWEQNuiscli395GKJOiPnPURNQWGvGCJZf4Hw yoqICbLIeYbpZPqDH4D8k4NKb04HqnrWBntEeVZEQ5gO1RmaUlln0Aqu1dj2UoF4 x-cyberduck-action:oauth

In AddClient.php line 111:
                                  
  The redirect URL is not valid.  
                                  

oauth2:add-client <name> <client-id> <client-secret> <redirect-url> [<allow-sub-domains> [<trusted> [<force-trust>]]]
```

**Comment by michaelstingl** [comment]
I just found, `x-cyberduck-action://oauth` can be added and Cyberduck works with it:

```
  - Cyberduck:
    - name: Cyberduck
    - redirect-url: x-cyberduck-action://oauth
    - client-id: 3keLfua0olYvW1zKXTDB3OjAMPEYWEQNuiscli395GKJOiPnPURNQWGvGCJZf4Hw
    - client-secret: yoqICbLIeYbpZPqDH4D8k4NKb04HqnrWBntEeVZEQ5gO1RmaUlln0Aqu1dj2UoF4
    - allow-sub-domains: false
    - trusted: false
```
